"""add_ranking_to_players

Revision ID: 14e1406a0a34
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 07:24:14.925523
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e1406a0a34'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('ranking', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_ranking'), 'players', ['ranking'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_ranking'), table_name='players')
    op.drop_column('players', 'ranking')
    # ### end Alembic commands ###
